 <h1 style="text-align:center;color:Blue">Numpy</h1>
 

<h2>NumPy is fundamental to many scientific and data analysis workflows in Python due to its efficiency and versatility.</h2>

In [671]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [672]:
import numpy as np

In [673]:
ls=[22,41,3,4,34,43]
ls

[22, 41, 3, 4, 34, 43]

In [674]:
arr=np.array(ls)
arr

array([22, 41,  3,  4, 34, 43])

In [675]:
a=arr[2]  
print(a)

3


In [676]:
type(arr)
## "numpy.ndarray" is a n dimensional array

numpy.ndarray

In [677]:
arr + 5

array([27, 46,  8,  9, 39, 48])

In [678]:
arr.ndim  ## no. of dimensions

1

In [679]:
[23,43,53]
## [[],[],[]] ==> its is a 2 dimensional array
arr.dtype  ## It shows the type of element of an array where it is integer or not.

dtype('int64')

In [680]:
ls=[23.1,23,54,33]
a=np.array(ls)
a.dtype
print(a)

[23.1 23.  54.  33. ]


In [681]:
i=[34,"rk",23.2,"True"]

In [682]:
a=np.array(i)

In [683]:
print(i)
a.dtype
## similar type of data is to be stored 
## array is a continuous memory allocation or a collection of similar item


[34, 'rk', 23.2, 'True']


dtype('<U32')

In [684]:
arr[2]

np.int64(3)

In [685]:
ls = [12,32,42,53,53,63,45,28,92,42]
arr = np.array(ls)
arr

# array creation
# item accessing
# item value manipulate

array([12, 32, 42, 53, 53, 63, 45, 28, 92, 42])

In [686]:
arr[2:6:3]

array([42, 63])

In [687]:
arr.size

10

In [688]:
len(arr) ## best example of polymorphism

10

In [689]:
arr
for i in ls:

    if i<50:
        print(i)

12
32
42
45
28
42


In [690]:
arr[arr<50] ## It gives the elements which was lesser than 50

array([12, 32, 42, 45, 28, 42])

In [691]:
arr.shape ## It shows the dimension and no. of elements present in array

(10,)

In [692]:
arr1=np.arange(1,50,2) # It returns elements upto 49 with step 2 and gives the array in one dimension 
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [693]:
np.ones((10,5)) ## It is a 2d array as like a matix of 1's

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [694]:
np.zeros((10,3)) ## It returns a 2d array with 10 row and 3 columns of 0's

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [695]:
np.zeros((10,5,6))  ## It return a 3d array of 10 2d matrix with 5 row and 6 column

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
    

In [696]:
np.linspace(1,8,5) ## In between 1-8,returns 5 items
np.linspace(1,50,100) ## In between 1-50, returns 100 items

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [697]:
import random  ## It is a inbuilt function which is used for generating random values

In [698]:
random.randint(1,10) ## It returns random value in between 1 to 10

5

In [699]:
random.random() ## It returns random value in between o to 1

0.21509324182330314

In [700]:
ls=['rubber','kartik jangir','ronak']

In [701]:
random.choice(ls) ## It returns random element from the list

'rubber'

In [702]:
random.choices(ls,k=2)  ## It returns 2 random element from the list

['ronak', 'kartik jangir']

In [703]:
ls

['rubber', 'kartik jangir', 'ronak']

In [704]:
random.shuffle(ls)  ## It suffles the item present in the list
print(ls)

['rubber', 'kartik jangir', 'ronak']


In [705]:
ls

['rubber', 'kartik jangir', 'ronak']

In [706]:
print(np.random.randint(1,50,10)) ## It return 1-d array in between 1-50(10 elements)

[47 27 41 39  4 22 16 34 25 44]


In [707]:
np.random.randint(0,2,(10,5))  ### It return 2-d array in between 0-2(10 rows and 5 columns)

array([[1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [0, 1, 1, 0, 1],
       [1, 1, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 1, 1, 0, 1],
       [0, 0, 0, 0, 1]], dtype=int32)

In [708]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [709]:
arr.reshape(12,int(5)) ## It returns an 3-d array with 12 rows and 5 columns and the total sum of the elements present in the aarray is 12*5=60

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [710]:

arr2=np.resize(arr,(25,25)) ## If multipule of before array is lesser than this array then the resize function is being used
arr2.shape

(25, 25)

In [711]:
arr2.ndim

2

In [712]:
arr2.reshape(25*25)  ## Both reshape and resize functions are same 
arr2.ravel()  ## It return the elment only in the 1-d array and prints the 625 elelments

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [713]:
arr2.flatten() ## Both ravel and flatten are same

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [714]:
arr=np.random.randint(5,50,100)  ## It return the 100 elements in between 5-50
arr

array([20,  9, 30, 18, 44, 40, 46, 40, 28, 12, 36, 22, 42, 19, 39, 42, 37,
       40, 33, 22, 33,  8, 33, 39, 38, 37, 28, 20, 49, 40, 49,  9, 36,  8,
       25, 32, 16, 17,  5, 37, 20, 10, 17, 11, 21, 19, 29, 10, 11, 26, 25,
       38, 39, 44, 10, 24,  9, 15,  8, 49, 32, 34, 38, 45, 24, 48, 17, 46,
       12, 43, 49, 20, 22, 35, 19, 43,  6, 26, 26, 25, 14, 18, 33, 38, 27,
       43, 18, 13, 28, 20, 12, 15, 11, 12, 45, 47, 31,  8, 47, 30],
      dtype=int32)

In [715]:
print(arr.mean()) ## Mean is a mathematical function which is used to calculate the average also max ans min functions is also used 

27.33


In [716]:
arr=np.random.randint(5,50,(4,3))  ##  It return a 2-d array in between 5-50 range with 4 rows and 3 columns
arr

array([[39, 27, 32],
       [17, 41, 49],
       [40, 25, 33],
       [16, 17, 33]], dtype=int32)

In [717]:
arr.shape  ## It determines the rows and column in the array

(4, 3)

In [718]:
np.transpose(arr).shape  ## It transpose or reverse the shape of the array with 3 rows and 4 columns

(3, 4)

In [719]:
arr.T  ## We also written transpose as T

array([[39, 17, 40, 16],
       [27, 41, 25, 17],
       [32, 49, 33, 33]], dtype=int32)

In [720]:
arr=np.random.randint(2,12,(10,5))  ## It returns 2-d array with random values in between 2-12 range with 10 rows and 5 columns 
arr

array([[ 7,  7,  3,  2,  9],
       [ 8, 10,  8,  7,  4],
       [ 6,  9,  6,  3,  8],
       [11, 10,  9, 10,  2],
       [11,  6,  9,  2,  3],
       [ 3,  6,  4, 11,  5],
       [11,  9,  4,  7,  9],
       [ 6, 10,  5, 11,  4],
       [10,  9,  7,  7,  9],
       [ 6,  2,  4,  8,  6]], dtype=int32)

In [721]:

np.ravel(arr)  ## It converts the 2-d array into 1-d array

array([ 7,  7,  3,  2,  9,  8, 10,  8,  7,  4,  6,  9,  6,  3,  8, 11, 10,
        9, 10,  2, 11,  6,  9,  2,  3,  3,  6,  4, 11,  5, 11,  9,  4,  7,
        9,  6, 10,  5, 11,  4, 10,  9,  7,  7,  9,  6,  2,  4,  8,  6],
      dtype=int32)

In [722]:
arr.reshape(50)

array([ 7,  7,  3,  2,  9,  8, 10,  8,  7,  4,  6,  9,  6,  3,  8, 11, 10,
        9, 10,  2, 11,  6,  9,  2,  3,  3,  6,  4, 11,  5, 11,  9,  4,  7,
        9,  6, 10,  5, 11,  4, 10,  9,  7,  7,  9,  6,  2,  4,  8,  6],
      dtype=int32)

In [723]:
arr.flatten()

array([ 7,  7,  3,  2,  9,  8, 10,  8,  7,  4,  6,  9,  6,  3,  8, 11, 10,
        9, 10,  2, 11,  6,  9,  2,  3,  3,  6,  4, 11,  5, 11,  9,  4,  7,
        9,  6, 10,  5, 11,  4, 10,  9,  7,  7,  9,  6,  2,  4,  8,  6],
      dtype=int32)

In [724]:
## 2-d array

arr[0]  ## It returns a first row of a given array

array([7, 7, 3, 2, 9], dtype=int32)

In [725]:
arr[-1]  ## It returns a last row of a given array

array([6, 2, 4, 8, 6], dtype=int32)

In [726]:
print(arr[2][1])  ## It returns a 1st element of 2nd row

9


In [727]:
print(arr[7:10])  ## It returns 7th , 8th and 9th row of the given array  

[[ 6 10  5 11  4]
 [10  9  7  7  9]
 [ 6  2  4  8  6]]


In [728]:
print(arr[0:,:2])  ## It returns upto last row of array and 2 column

[[ 7  7]
 [ 8 10]
 [ 6  9]
 [11 10]
 [11  6]
 [ 3  6]
 [11  9]
 [ 6 10]
 [10  9]
 [ 6  2]]


In [729]:
print(arr[-10:,:-3]) ## It returns 10 rows from bottom and 3 columns from the last 

[[ 7  7]
 [ 8 10]
 [ 6  9]
 [11 10]
 [11  6]
 [ 3  6]
 [11  9]
 [ 6 10]
 [10  9]
 [ 6  2]]


In [730]:
print(arr[3:6,2:])  ## It returns 3 rows between 3-6 and returns columns from 2 upto last

[[ 9 10  2]
 [ 9  2  3]
 [ 4 11  5]]


In [731]:
print(arr[0::2,2:])  ## It returns a array upto rows with a step of 2 and columns after 2 upto last

[[3 2 9]
 [6 3 8]
 [9 2 3]
 [4 7 9]
 [7 7 9]]


In [732]:
# 3D array

arr=np.random.randint(2,50,(5,10,5))  
arr

array([[[37, 11, 48, 35,  8],
        [29, 27, 16, 47, 32],
        [17, 28, 17, 41, 18],
        [ 8, 23, 20, 34, 12],
        [40, 12, 39,  6, 21],
        [43, 45, 48, 27, 35],
        [34, 21, 41, 31, 46],
        [32, 47, 46, 17, 17],
        [12, 17, 17, 23,  4],
        [10, 23, 20, 27, 10]],

       [[ 9, 38, 37, 48, 43],
        [41, 30,  7, 18, 38],
        [28, 38, 31, 21, 36],
        [35, 30, 10, 42,  4],
        [17, 36, 28, 19, 29],
        [48, 43, 30, 32, 14],
        [23,  9, 36,  5, 28],
        [20, 33, 34, 19, 48],
        [29, 40, 44, 28, 16],
        [19, 27, 41, 42, 48]],

       [[ 9, 44, 46, 36, 24],
        [30,  2, 40, 21,  6],
        [39, 35, 37, 47, 38],
        [11, 23, 33, 18, 24],
        [24, 14,  6, 15, 31],
        [29, 42, 21, 20, 35],
        [ 6, 46,  7, 33, 11],
        [30, 43,  7,  7, 38],
        [16, 22, 37, 18, 22],
        [12, 15, 39, 29, 49]],

       [[41, 15, 34, 19, 42],
        [13, 37, 18, 18,  9],
        [48, 31, 26, 39, 14],
    

In [733]:
arr.shape
# 5=tables , 10=rows ,5=columns

(5, 10, 5)

In [734]:
print(arr.ndim)

3


In [735]:
arr[0] ## If we pass single value it return first position table

array([[37, 11, 48, 35,  8],
       [29, 27, 16, 47, 32],
       [17, 28, 17, 41, 18],
       [ 8, 23, 20, 34, 12],
       [40, 12, 39,  6, 21],
       [43, 45, 48, 27, 35],
       [34, 21, 41, 31, 46],
       [32, 47, 46, 17, 17],
       [12, 17, 17, 23,  4],
       [10, 23, 20, 27, 10]], dtype=int32)

In [736]:
print(arr[0:,9:,:]) ## Accessing items from array

[[[10 23 20 27 10]]

 [[19 27 41 42 48]]

 [[12 15 39 29 49]]

 [[44 13 34 27 49]]

 [[27 31 43 15 18]]]


In [737]:
arr=np.array([7,5,9])
arr

array([7, 5, 9])

In [738]:
print(arr.max()) # it return the maximum value

9


In [739]:
print(arr.argmax()) # argmax return the index value

2


In [740]:
print(arr.sort())


None


In [741]:
arr

array([5, 7, 9])

In [743]:
arr.argsort()
# it return the index value of sorted array

array([0, 1, 2])

In [744]:
arr=np.random.randint(2,12,(10,5))

In [745]:
arr

array([[ 5,  3, 10, 11,  9],
       [ 8,  8,  5,  2,  3],
       [ 5,  9,  9,  8,  9],
       [ 6,  7,  7,  2, 10],
       [ 4,  6, 11,  8,  4],
       [ 8,  2, 11,  5,  6],
       [ 2,  3, 11,  6,  9],
       [ 2,  7,  6,  5,  6],
       [ 8,  8,  5, 10,  4],
       [ 8,  4,  8,  8,  7]], dtype=int32)

In [746]:
np.unique(arr)  ## It returns the one value only once

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [747]:
arr

array([[ 5,  3, 10, 11,  9],
       [ 8,  8,  5,  2,  3],
       [ 5,  9,  9,  8,  9],
       [ 6,  7,  7,  2, 10],
       [ 4,  6, 11,  8,  4],
       [ 8,  2, 11,  5,  6],
       [ 2,  3, 11,  6,  9],
       [ 2,  7,  6,  5,  6],
       [ 8,  8,  5, 10,  4],
       [ 8,  4,  8,  8,  7]], dtype=int32)

In [748]:
print(arr.mean())  ## It return mean

6.56


In [749]:
arr=np.random.randint(2,250,200)
arr

array([164,  30, 172, 168,  84,  21, 147, 137, 181, 109,  98,  94,  80,
        37, 142, 212,  97, 147, 192,   9, 234,  74, 112,  70, 139, 188,
        87, 129, 127, 183,  24, 114,  98,  59,  77, 135, 190, 197,  45,
       204, 204, 171, 142, 195, 248, 181, 237, 248, 117,  35,  15, 247,
        28, 197, 207, 163,  34, 158, 206,  45, 188, 170, 184, 207, 211,
       150,  19, 205,  37, 107, 168, 169,  33, 173, 147, 154,  60, 113,
       156, 229, 232, 159,  35, 141, 203, 211, 137,  14,  57, 137, 177,
       232,   5, 106, 133, 146, 103,  81, 224,  72,  18,  84, 160, 247,
       178, 200, 129, 184, 187, 181,   8,  49, 112, 242, 177,  20, 126,
        90,  90,  62,  75, 193,  50, 241,  35,  87, 144,  80, 162, 246,
       161,  38, 239, 214,  75,  13, 200,   2,   7,  53, 135, 239,  48,
       103, 239, 166,  36,  54, 195, 169, 157,  38, 207, 161, 170, 150,
        23,  34, 158, 189,  84, 219, 171,  46, 100, 166,  51,  32, 220,
       178, 118,  76, 152, 190,  40, 118, 186, 117, 106, 101,  8

In [750]:
np.median(arr) ## It returns median

np.float64(135.0)

In [751]:
arr.var()

np.float64(4775.2099)

In [752]:
print(arr.std())  ## it returns the standard deviation 

69.10289357183242


In [753]:
print(np.sqrt(25)) ## it returns the square root of the element

5.0
